### ISSUE TITLE
Unable to load extension 

### ISSUE THREAD

**Issue by MotherShip808** [peace-maker/DHooks2#1]
Getting this error in console on startup.

`L 04/30/2020 - 22:41:11: [SM] Unable to load extension "dhooks.ext": Could not find interface: ISourceMod`

**Comment by MotherShip808** [comment]
I am running the latest version from here https://github.com/peace-maker/DHooks2/releases/tag/v2.2.0-detours10

**Comment by peace-maker** [comment]
Whats your SourceMod versin on the server exacltly?
`sm version`

**Comment by MotherShip808** [comment]
SourceMod Version Information:
    SourceMod Version: 1.9.0.6281
    SourcePawn Engine: 1.9.0.6281, jit-x86 (build 1.9.0.6281)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: May 14 2019 16:03:05
    Built from: https://github.com/alliedmodders/sourcemod/commit/c5efe48
    Build ID: 6281:c5efe48

**Comment by peace-maker** [comment]
are you running the right version? not the one for sm110?
