### ISSUE TITLE
Crash on Centos 7

### ISSUE THREAD

**Issue by 39ma** [peace-maker/DHooks2#11]
Hello.
Tested DHooks + Detour on Centos 7 and Debian.
On Debian it works well without issues.
But on Centos 7 its gives crash (Segmentation Fault).

Info:
https://crash.limetech.org/p6ls5a3x4iom

Command Line
./srcds_linux -game csgo -usercon -strictportbind -ip 79.143.20.74 -port 27015 +clientport 27017 +tv_port 27016 -tickrate 128 +map de_dust2 +servercfgfile server.cfg -maxplayers_override 20 +game_mode 0 +game_type 0 +host_workshop_collection +workshop_start_map -authkey ******************************** -nobreakpad +sv_setsteamaccount ******************************** -debug -steam

Extension Version
2.5.0
Game Directory
csgo
Game Path
/home/test/serverfiles/csgo
SourceMod Path
/home/test/serverfiles/csgo/addons/sourcemod
SourceMod Version
1.10 - 16.03.2019
Steam Client Version
1187
Steam Patch Version
1.37.7.0
Steam Product Name
csgo
Steam Server Version
1187
Steam Source Revision
6147270
Steam Version Date
Oct 15 2020
Steam Version Time
17:25:32
Steam App ID
730

**Comment by peace-maker** [comment]
And the server doesn't crash with dhooks disabled?

**Comment by 39ma** [comment]
> And the server doesn't crash with dhooks disabled?

yep. I use same test plugin in Debian 10.6.0 and CentOS 7.
Clean CS:GO server with fresh metamod and sourcemod.
But on CentOS 7 its crashing when I call a function from DHooks.
Gameserver with dhooks detour starting normally without any incedents on CentOS.
But when prehook is called, posthook crashing server.
Same situation in Debian working stable without any incedents.

**Comment by peace-maker** [comment]
The crash you've linked is one in the engine on map start after printing a warning `GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom)`. I don't see the relation to dhooks there :/ Do you have a link for a crash in a post hook?
