### ISSUE TITLE
Crash on removing ent

### ISSUE THREAD

**Issue by Ilusion9** [peace-maker/DHooks2#13]
https://crash.limetech.org/gd2tysruj7hp

I've been using this: https://forums.alliedmods.net/showthread.php?t=319141
If i remove an hooked entity the server crashes

I dhook AcceptInput and remove with AcceptEntityInput

**Comment by peace-maker** [comment]
Can you provide a test plugin I can use to debug this please?

**Comment by peace-maker** [comment]
@Ilusion9 Do you have a short test case reproducing this issue?

**Comment by Ilusion9** [comment]
https://forums.alliedmods.net/showpost.php?p=2746919&postcount=20
solved
