### ISSUE TITLE
No way to check if pointer is pointing to a null value for CBaseEntity and Edict type of param

### ISSUE THREAD

**Issue by GAMMACASE** [peace-maker/DHooks2#15]
Currently you can only check if the address itself is a null if I'm reading the code [here](https://github.com/peace-maker/DHooks2/blob/a323ffc72d30e3a606224a0664471ae7596432c7/natives.cpp#L1403) correctly, but when you are getting a param of a type CBaseEntity or Edict it'll check the value stored in the pointer and if it's a NULL it'll error about it [here](https://github.com/peace-maker/DHooks2/blob/a323ffc72d30e3a606224a0664471ae7596432c7/natives.cpp#L618-L621). So currently there's no way to check if you can safely get the entity or edict from a param or not and it'll always error if it's NULL. In my test case ``DHookIsNullParam()`` returned ``false`` and skipped my if block, so it resulted in a "Exception reported: Trying to get value for null pointer".

Test code snippet:
```
	if(DHookIsNullParam(hParams, 5))
		return MRES_Ignored;
	
	int val = DHookGetParam(hParams, 5);
```
Error happens on the ``int val = DHookGetParam(hParams, 5);`` line.

**Comment by peace-maker** [comment]
Was your detour setup with at least one parameter passed through a custom register? I've just fixed a bug with DHookIsNullParam, but can't test your usecase.

**Comment by peace-maker** [comment]
Fix confirmed through Discord.
