### ISSUE TITLE
Crash on Plugin Unload

### ISSUE THREAD

**Issue by Blunderstab** [peace-maker/DHooks2#17]
While using https://github.com/nosoop/SM-TFOnTakeDamage, server crashes can happen when plugins are unloaded.

This was happening while I had an SDKHook for OnTakeDamageAlive.

```
public void OnClientPutInServer(int player) {
	SDKHook(player, SDKHook_OnTakeDamageAlivePost, OnTakeDamageAlivePost);
}
```
If all plugins were active when I joined the server, unloading plugins would cause a crash. If TFOnTakeDamage, DHooks, or the plugin with the SDKHook were inactive upon joining the server and then loaded in, unloading the plugins would not cause a server crash.

I just updated to DHooks (2.2.0-detours16), and my SM version is 1.10.0.6488. I was using 14a previously, I believe.

**Comment by peace-maker** [comment]
Could you please install Accelerator and link to one of those crashes?

**Comment by Blunderstab** [comment]
Oops, I'd already done that and just forgotten it! Haha
https://crash.limetech.org/g4xzsew4f53j

**Comment by peace-maker** [comment]
Can you test if this issue was fixed in the latest release of detours17 please?

**Comment by Blunderstab** [comment]
Seems to be fine now.
