### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xhaooy** [peace-maker/DHooks2#6]
hi, i had this crash earlier today:
https://crash.limetech.org/ws36abz3dyx4

aaaaaaaaaaand thank you for your work on this

**Comment by peace-maker** [comment]
I think this should be fixed with https://github.com/peace-maker/DHooks2/commit/9b9454b14c7525550757b74e9c27e65ac8d5fb4f which isn't in a new release yet.

I really need to setup some CI or automatic builds for this..

**Comment by xhaooy** [comment]
ok thanks

**Comment by xhaooy** [comment]
alright im back, maybe you can compile latest commit and share with us?
and now im getting this: https://crash.limetech.org/i7cep3wweji6

**Comment by xhaooy** [comment]
could you or this is unstable for release?

**Comment by Erik-97** [comment]
Hello peace-maker! Please compile the latest source code and upload a release. i tried a lot of ways to compile it but i had no success, 2 days of research but i couldn't do it. Thanks

**Comment by peace-maker** [comment]
The commit is included in the latest release.
https://github.com/peace-maker/DHooks2/releases/tag/v2.2.0-detours15
