### ISSUE TITLE
INVALID_HOOK_ID should be 0 instead of -1

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [peace-maker/DHooks2#9]
Before transitional syntax update, include docs said that -1 is returned if hooking failed, but [0 is actually returned instead](https://github.com/peace-maker/DHooks2/blob/2ccd565be945a8afc92ce4ac54eaf1c97339446e/natives.cpp#L417-L421). I think SourceHook returns 0 if hook failed anyway?

Since `INVALID_HOOK_ID` is new, I'd recommend change it to 0 rather than updating extension to return -1, which would break older plugins.

**Comment by peace-maker** [comment]
Oh, you're right, I was blindly going after the docs. PRs welcome 😉
